# Generated by Django 4.2.3 on 2023-07-27 12:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_characterictics_item_characteristics_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'Product image',
            },
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type bien'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_image9',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.imagemodel'),
        ),
    ]
