# Generated by Django 4.2.3 on 2023-07-28 16:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='primary_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
