# Generated by Django 4.2.3 on 2023-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_languages_job_contract_type_job_durée_job_heures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Niveau',
            },
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Langue'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='durée',
        ),
        migrations.AddField(
            model_name='job',
            name='period',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='niveau',
            field=models.ManyToManyField(default=None, to='core.niveau'),
        ),
    ]
