# Generated by Django 4.2.3 on 2023-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_category_job_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
