# Generated by Django 4.2.3 on 2023-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ad_title_alter_characteristics_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
