# Generated by Django 4.2.3 on 2023-07-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_item_item_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_characteristics',
            options={'verbose_name': 'Characteristique produit'},
        ),
        migrations.AlterModelOptions(
            name='job_characteristics',
            options={'verbose_name': 'Characteristique job'},
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
