# Generated by Django 4.2.3 on 2023-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_slug_alter_job_langues_alter_job_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
