# Generated by Django 4.2.3 on 2023-08-02 11:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.user_directory_path_job),
        ),
    ]
